version: "3.9"
services:

  postgres:
    image: postgres
    command: postgres -c 'max_connections=200'
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "docker"
      POSTGRES_DB: "newsletter"


  jaeger:
    image: jaegertracing/all-in-one:1.17.1
    command: [ "--log-level=debug" ]
    ports:
      - "10000:16686"
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"


  otlp-collector:
    image: otel/opentelemetry-collector:latest
    command: [ "--config=/etc/otlp-collector-config.yaml", "--log-level=debug" ]
    depends_on:
      - jaeger
    volumes:
      - ./otlp-collector-config.yaml:/etc/otlp-collector-config.yaml
    ports:
      - "9000:9000"
      - "9001:9001"