version: "3.9"
services:

  postgres:
    image: postgres
    command: postgres -c 'max_connections=200'
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "docker"
      POSTGRES_DB: "newsletter"


 