

extensions:
  zpages:
    endpoint: "0.0.0.0:55679"

processors:
  batch:

exporters:
  logging:
  jaeger:
    endpoint: "jaeger:14250"
    insecure: true

service:
  extensions: [zpages]
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ jaeger ]

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:9000"
      http:
        endpoint: "0.0.0.0:9001"