receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "otlp-collector:9000"

processors:
  batch:

exporters:
  logging:
  jaeger:
    endpoint: "jaeger:14250"
    insecure: true

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ jaeger ]